version: '3'
services:
  web:
    build: .
    entrypoint: ./docker-rails.sh
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - HOST_NAME=${HOST_NAME}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/rails-8-starter